project_name        = "nodejs"
project_environment = "production"
instance_type       = "t2.micro"
ami_id              = "ami-0a1235697f4afa8a4"
domain_name         = "chottu.shop"
hostname            = "nodejs-app"
vpc_cidr_block      = "172.16.0.0/16"
enable_nat_gw       = true
loadbalancer_ports = ["8080", "443"]
